apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - image: jennykibiri/reactapp
        name: reactapp
        ports:
        - containerPort: 80
