apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: reactapp
        ports:
        - containerPort: 80
